from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

EVENTS_PROCESSED = Counter("events_processed_total", "Events successfully processed", ["source", "event_type"])
EVENTS_FAILED = Counter("events_failed_total", "Events which failed processing", ["source", "event_type"])
DUPLICATE_EVENTS = Counter("duplicate_events_total", "Duplicate event deliveries", ["source"])
EVENT_PROCESSING_DURATION = Histogram("event_processing_duration_seconds", "End-to-end event processing duration", ["event_type"])
TWIN_UPDATE_DURATION = Histogram("twin_update_duration_seconds", "Digital twin update duration", ["event_type"])
CONTEXT_BUILD_DURATION = Histogram("context_build_duration_seconds", "Context construction duration", ["event_type"])
ACTION_GENERATION_DURATION = Histogram("action_generation_duration_seconds", "Action generation duration", ["event_type"])
OUTBOX_PENDING = Gauge("outbox_pending_total", "Outbox messages awaiting delivery")
OUTBOX_FAILED = Gauge("outbox_failed_total", "Outbox messages dead-lettered")
VERSION_CONFLICTS = Counter("version_conflicts_total", "Optimistic concurrency conflicts", ["model"])
REPLAY_DURATION = Histogram("replay_duration_seconds", "Replay duration", ["plant_id"])
RULE_EXECUTIONS = Counter("rule_executions_total", "Rule executions", ["rule", "outcome"])
GRAPH_NODES = Gauge("graph_nodes_total", "Current graph nodes", ["node_type"])
GRAPH_RELATIONSHIPS = Gauge("graph_relationships_total", "Current graph relationships", ["relationship_type"])
GRAPH_UPDATES = Counter("graph_updates_total", "Graph synchronization updates", ["result"])
GRAPH_SYNC_SUCCESS = Counter("graph_sync_success_total", "Successful graph synchronizations")
GRAPH_SYNC_FAILURE = Counter("graph_sync_failure_total", "Failed graph synchronizations")
GRAPH_SYNC_DURATION = Histogram("graph_sync_duration_seconds", "Graph synchronization duration")
GRAPH_QUERY_DURATION = Histogram("graph_query_duration_seconds", "Graph query duration", ["query"])
GRAPH_REBUILD_DURATION = Histogram("graph_rebuild_duration_seconds", "Graph rebuild duration", ["mode"])
GRAPH_REPLAY_DURATION = Histogram("graph_replay_duration_seconds", "Replay graph synchronization duration")
GRAPH_REVISION_LAG = Gauge("graph_revision_lag", "Twin to graph revision lag", ["plant_id"])
GRAPH_FAILED_RECOVERIES = Counter("graph_failed_recoveries_total", "Failed graph recoveries")
GRAPH_TEMPORAL_RELATIONSHIPS = Counter("graph_temporal_relationships_total", "Temporal relationship versions", ["relationship_type"])
