from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    GAS_SENSOR = "GAS_SENSOR"
    TEMPERATURE_SENSOR = "TEMPERATURE_SENSOR"
    PRESSURE_SENSOR = "PRESSURE_SENSOR"
    VIBRATION_SENSOR = "VIBRATION_SENSOR"
    HOT_WORK = "HOT_WORK"
    CONFINED_SPACE = "CONFINED_SPACE"
    ELECTRICAL = "ELECTRICAL"
    EXCAVATION = "EXCAVATION"
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    PPE_VIOLATION = "PPE_VIOLATION"
    START = "START"
    COMPLETE = "COMPLETE"
    FIRE = "FIRE"
    LEAK = "LEAK"
    EXPLOSION = "EXPLOSION"
    NEAR_MISS = "NEAR_MISS"
    WORKER_DETECTED = "WORKER_DETECTED"
    WORKER_LOST = "WORKER_LOST"
    SMOKE_DETECTED = "SMOKE_DETECTED"
    FIRE_DETECTED = "FIRE_DETECTED"
    GAS_CLOUD_DETECTED = "GAS_CLOUD_DETECTED"
    RESTRICTED_AREA_VIOLATION = "RESTRICTED_AREA_VIOLATION"
    VEHICLE_DETECTED = "VEHICLE_DETECTED"
    WORKER_FALL = "WORKER_FALL"

class EventSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class ActionType(StrEnum):
    RESTRICTED_ZONE_ENTRY = "RESTRICTED_ZONE_ENTRY"
    PERMIT_EXPIRED = "PERMIT_EXPIRED"
    EQUIPMENT_OFFLINE = "EQUIPMENT_OFFLINE"
    WORKER_EXIT = "WORKER_EXIT"
    MAINTENANCE_STARTED = "MAINTENANCE_STARTED"
    PPE_VIOLATION = "PPE_VIOLATION"
    HAZARD_DETECTED = "HAZARD_DETECTED"
    EVACUATE_ZONE = "EVACUATE_ZONE"
    SUSPEND_PERMIT = "SUSPEND_PERMIT"
    SHUTDOWN_EQUIPMENT = "SHUTDOWN_EQUIPMENT"
    NOTIFY_SUPERVISOR = "NOTIFY_SUPERVISOR"
    LOCK_EQUIPMENT = "LOCK_EQUIPMENT"
    INCREASE_MONITORING = "INCREASE_MONITORING"
    DISPATCH_INSPECTION = "DISPATCH_INSPECTION"


class ActionStatus(StrEnum):
    PENDING = "PENDING"
    EMITTED = "EMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
